parameters:
#    cobania_admin.example.class: Cobania\AdminBundle\Example

services:
#    cobania_admin.example:
#        class: %cobania_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
